### ISSUE TITLE
Custom scopes require userinfo endpoint

### ISSUE THREAD

**Issue by nsklikas** [IdentityPython/oidcendpoint#27]
To define custom scopes the userinfo endpoint needs to be defined, but in the case of implicit flow the userinfo isn't needed. Shouldn't custom scopes be decoupled from userinfo?

In addition, custom scopes are not taken into account when defining the supported scopes in the authorization endpoint (only the scopes defined in `SCOPE2CLAIMS` are used there), is this intentional? IMO custom scopes should be added to the default supported scopes.

**Comment by rohe** [comment]
Good points. I'll have a look.

**Comment by peppelinux** [comment]
Means that we should have a db configured for the token and the same, or another one, for the enduser endpoint... Sounds good, because they could be also the same.

**Comment by rohe** [comment]
I think we should stay with having the same set of scopes for all endpoints.
One set for the OP/AS as such.
The connection to userinfo endpoint can easily be severed. 
You MUST be able to define custom scopes disregarding which endpoints the service can serve.

**Comment by rohe** [comment]
Regarding the use of DEFAULT_SCOPES for the authorisation endpoint that is just if nothing else is defined. If you add custom scopes the authorisation endpoint will use the new set (custom+default) as will all the other endpoints.
