### ISSUE TITLE
Registration endpoint - available scopes for clients

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/oidcendpoint#28]
Could we think to configure wich scopes could be released to clients? 

I didn't found this filter and not developed this in django-oidc-op. Is there something I missed or we could add this feature as well?

I'd like to add this feature as a many2one in the registration ui:
https://github.com/peppelinux/django-oidc-op/blob/master/images/rp.png

**Comment by rohe** [comment]
There is presently no way to defined specific scope releases per client.
In a federated environment this can be very challenging to manage.

**Comment by peppelinux** [comment]
Ok, We'll discuss the federation scenarios in idem oidc-wg next month, then I'll update or close this thread
