### ISSUE TITLE
Token introspection endpoint response for invalid requests

### ISSUE THREAD

**Issue by angelakis** [IdentityPython/oidcendpoint#33]
Right now, the token introspection endpoint responds with active = False in all requests even if, for example, the token parameter is missing. Should the case of invalid or malformed requests be handled in another way, e.g. with a HTTP 400?

The RFC states ```"Note that a properly formed and authorized query for an inactive or
   otherwise invalid token (or a token the protected resource is not
   allowed to know about) is not considered an error response by this
   specification."```, however a request without a token parameter probably should not be considered properly formed.

**Comment by rohe** [comment]
Probably right.

**Comment by rohe** [comment]
Now, whether it should be a HTTP 400 response or something different anyones guess.
We should follow what RFC6749 says which some have interpreted as stating that you can return a 200 (or 302 where applicable) with an error message.
Myself I think I'd prefer a 400 with an error message.
Similar to what OIDC says on token endpoint errors:
https://openid.net/specs/openid-connect-core-1_0.html#TokenErrorResponse

**Comment by rohe** [comment]
The code is changed to not accept a malformed request.

**Comment by angelakis** [comment]
Great, thanks!
