### ISSUE TITLE
Authorization response invalid content-type when using form_post

### ISSUE THREAD

**Issue by nsklikas** [IdentityPython/oidcendpoint#34]
The authorization endpoint allows three possible `response_modes`: `query`, `fragment` and `form_post`.

According to https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html#FormPostResponseMode:

> In this mode, Authorization Response parameters are encoded as HTML form values that are auto-submitted in the User Agent, and thus are transmitted via the HTTP POST method to the Client, with the result parameters being encoded in the body using the application/x-www-form-urlencoded format

BUT when an authorization request is made using `response_mode = form_post` the endpoint will return a response with `content-type = application/x-www-form-urlencoded` (it should be `text/html`).  The content-type is set in https://github.com/IdentityPython/oidcendpoint/blob/4a761b146e0d1a046c26ed65ab1811df560ac409/src/oidcendpoint/endpoint.py#L345

I don't know if this affects any other endpoints, so I'm not sure how this should be fixed.

**Comment by rohe** [comment]
I'll take care of it. Will do it before Monday. Can't promise more then that :-)

**Comment by rohe** [comment]
Checked in something that hopefully will take care of this.
