### ISSUE TITLE
Token endpoint

### ISSUE THREAD

**Issue by nsklikas** [IdentityPython/oidcendpoint#38]
Currently there are two `Endpoint`s (as in oidcendpoint classes) that implement the token endpoint, the `AccessToken` (`src/oidcendpoint/oidc/token.py`) and `RefreshAccessToken` (`src/oidcendpoint/oidc/refresh_token.py`). 

In order to implement the token endpoint in SATOSA I would have to check the grant_type in the request and call the corresponding oidcendpoint endpoint (ie if `grant_type=refresh_token` then use `RefreshAccessToken`). This decision should be made in oidcendpoint since it is the one parsing the request.

Shouldn't these two classes be merged?

**Comment by rohe** [comment]
I'd like to state for the record that I've never liked the decision to have 2 services (token and refresh_token) listen on the same endpoint.
So far I've had the decision in the webserver but I would be OK to push it down into oidcendpoint.
I'll have a look at what it would take to merge the two classes.
There would for instance have to be some configuration options added since an OP could support token but not refresh_token.

**Comment by rohe** [comment]
OK, I've pushed a new Endpoint and a test of the same.
Use oidcendpoint.oidc.token_coop.TokenCoop as you would have used oidcendpoint.oidc.token.Token.

You can turn off the refresh token functionality by setting allow_refresh=False in the configuration of the token endpoint.

**Comment by peppelinux** [comment]
> You can turn off the refresh token functionality by setting allow_refresh=False in the configuration of the token endpoint.

Is this correct?
https://github.com/peppelinux/django-oidc-op/blob/master/example/example/oidc_op.conf.yaml#L153

**Comment by rohe** [comment]
Yes!

**Comment by nsklikas** [comment]
I don't think you had to create a new flag for configuring whether the refresh token should work.
We could check whether there exists a refresh token handler or if the refresh_token grant type is supported.

This brings me to another issue. With the current implementation the token endpoint can issue refresh tokens even if the refresh_token grant type is not supported, is this intentional?

**Comment by rohe** [comment]
Good point.
No it's not intentional.
I'll deal with it.

**Comment by rohe** [comment]
Allow refresh token handling is now dependent on refresh token handler being available and refresh_token grant type being supported.
