### ISSUE TITLE
Token Introspection works only for JWT

### ISSUE THREAD

**Issue by angelakis** [IdentityPython/oidcendpoint#39]
The RFC [1] mentions some JWT specific  attributes in the response, but token introspection should work with normal access tokens as well. The offending line: https://github.com/IdentityPython/oidcendpoint/blob/79fd7f8c3589932c7136baf8a2018b7934c2946a/src/oidcendpoint/oauth2/introspection.py#L51

[1] https://tools.ietf.org/html/rfc7662

**Comment by rohe** [comment]
So that lines makes an assumption and that is that the token is a JWT.
You're right in that doesn't have to be the case.
Will look at this.

**Comment by rohe** [comment]
Modified the code to deal with JWT tokens and non-JWT access tokens.
