### ISSUE TITLE
Bug in Token handler info

### ISSUE THREAD

**Issue by angelakis** [IdentityPython/oidcendpoint#44]
The info method tries to find the correct handler for the token by using a try-except and moving to the next token type (`order`) in case of some exceptions. However, if the access or refresh token is configured to be a JWT, the exception raised is `cryptojwt.exception.BadSyntax` which is not handled.

This is the point where `cryptojwt.exception.BadSyntax`, but I am not sure if there are other exceptions that should be added too:
https://github.com/IdentityPython/oidcendpoint/blob/059636d2d9c52a7a8d62aadea6d2141acf3fbc32/src/oidcendpoint/token_handler.py#L221

**Comment by rohe** [comment]
I'll have a look.

**Comment by rohe** [comment]
Dealt with.
