### ISSUE TITLE
"none" authentication method broken

### ISSUE THREAD

**Issue by angelakis** [IdentityPython/oidcendpoint#50]
Is "none" authn method still supported? Because the recently introduced client_auth_setup requires a known method or a class and None raises an exception when it's about to be imported.

Check here:
https://github.com/IdentityPython/oidcendpoint/blob/46742a44e18456583753e33907340e2f6e5c1063/src/oidcendpoint/client_authn.py#L382

I can still configure an endpoint to not have client authentication by not providing a client_authn_method argument in the kwargs, however I can see the None method in the CLIENT_AUTHN_METHOD dict and also here:
https://github.com/IdentityPython/oidcendpoint/blob/46742a44e18456583753e33907340e2f6e5c1063/src/oidcendpoint/endpoint.py#L286

So I am not sure if it's still supported or not.

Suggested solution:
Handle None case in client_auth_setup.

**Comment by rohe** [comment]
I agree, one should be able to specify no authentication beside an accepted authentication method. I'll fix.

**Comment by rohe** [comment]
So there is a number of cases.

1) A specific set of client auth metods is listed ('none' can be one of them)
2) client_authn_method is not set to anything => the default set (if there is one) is used.
3) client_authn_method is set to nothing (== '',[]) => 'none' is the only allowed auth method.

See the difference between test_verify_client_authorization_none() and test_verify_client_registration_none() in tests/test_02_client_authn.py
