### ISSUE TITLE
Scopes per RP

### ISSUE THREAD

**Issue by angelakis** [IdentityPython/oidcendpoint#55]
Is it possible to support scopes allowed per RP/client? So that each client is allowed to only ask for a subset of supported scopes. It could be configured/saved in the client database.

**Comment by rohe** [comment]
I would say it SHOULD be in the client database.
It's not there right now so we have to add it.
When I'm done with my present engagement (in a couple of days) I can have a look at it.
If you feel like it give me a PR :-)

**Comment by peppelinux** [comment]
Great to hear that, this also references this:
https://github.com/IdentityPython/oidcendpoint/issues/28

I need this definition in django-oidc-op, I would implemet them here:
https://github.com/peppelinux/django-oidc-op/blob/master/oidc_op/models.py#L40

**Comment by rohe** [comment]
I've started work on this.

So this is the layout right now.

1) If nothing is specified, default available scopes and claims are given by ```SCOPE2CLAIMS```.

2) You can add scopes/claims using the custom_scopes add_on

3) You can restrict default available scopes/claims by setting endpoint_context.provider_info['supported_claims'] and  endpoint_context.provider_info['supported_scopes'] .

Changing supported_scopes will affect default available claims.

4) You can per client ID set ```allowed_scopes```

This is where I'm at right now.

**Comment by rohe** [comment]
I've refactored the scopes stuff so it now appears in a module of its own.
A class (Scopes) with one method ```allowed_scopes``` defined.
I expect to subclass this to deal with federation use cases. Like differences in release of attributes dependent on federation type, trust marks, ...
Things that are not specifically bound to a client but rather to the context.

**Comment by peppelinux** [comment]
I'm going to implement and test this features, so I think to keep this open untill job is done if you agree

**Comment by peppelinux** [comment]
In oidcrp.__init__, `init_authorization`, I can read the scopes configured in client_preferencies. I put `that_scope` for example.

````
509  	        # Need a new state for a new authorization request
510  	        _state = client.session_interface.create_state(service_context.get('issuer'))
511  	        request_args['state'] = _state
512  	        client.session_interface.store_nonce2state(_nonce, _state)
513  	        import pdb; pdb.set_trace()
514  ->	        logger.debug('Authorization request args: {}'.format(request_args))
515  	
516  	        _srv = client.service['authorization']
517  	        _info = _srv.get_request_parameters(request_args=request_args)
518  	        logger.debug('Authorization info: {}'.format(_info))
519  	        return {'url': _info['url'], 'state': _state}
(Pdb) _state
'ptUvN9ZQIt7ZxC38KWyWz1HsskFKXL1Z'
(Pdb) request_args
{'redirect_uri': 'https://127.0.0.1:8099/authz_cb/django_oidc_op', 'scope': ['openid', 'that_scope', 'profile', 'email', 'address', 'phone'], 'response_type': 'code', 'nonce': 'JuVJsLovMZHTamZlt1klQ4U0', 'state': 'ptUvN9ZQIt7ZxC38KWyWz1HsskFKXL1Z'}
````

then I can read `_info` as:
```
{'method': 'GET', 'url': 'https://127.0.0.1:8000/authorization?redirect_uri=https%3A%2F%2F127.0.0.1%3A8099%2Fauthz_cb%2Fdjango_oidc_op&scope=openid+that_scope+profile+email+address+phone&response_type=code&nonce=JuVJsLovMZHTamZlt1klQ4U0&state=ptUvN9ZQIt7ZxC38KWyWz1HsskFKXL1Z&code_challenge=AWdTzmuvWixa4Ozvsm9l2ywhgp0FHRFm2xf6h-5ZMhQ&code_challenge_method=S256&client_id=1UUl6cwNigmj'}
````

Everything works fine, access token is released correctly:
![image](https://user-images.githubusercontent.com/1297620/88599680-a1ee0f00-d06c-11ea-870b-decb536120d3.png)
