### ISSUE TITLE
Non-default claims in IDToken

### ISSUE THREAD

**Issue by nsklikas** [IdentityPython/oidcendpoint#63]
The claims that will be added in the id token are chosen via the `by_schema` function in `oidcendpoint/userinfo.py`. Which by default uses the `oidcmsg.oidc.IdToken` class to choose whether a claim should be added or not.

I am not sure if this is intentional or not, because if extra claims/scopes are added then they will not be returned in the IDToken since they are not in the default OIDC claims, unless a custom `id_token_schema` is provided in the configuration.

I think that the claims shouldn't be filtered like this (perhaps the call to `by_schema` should be removed altogether).

I hope the problem I describe is clear, do you think this should be changed or should we simply extend the `id_token_schema` to include our extra claims?

**Comment by nsklikas** [comment]
To add on to that, I think that the claims requested from scopes are added to the ID token only when the `response_type="id_token"` is this intentional?

**Comment by rohe** [comment]
I get your point. I'll have a look.
Will probably not have time until tomorrow.
I think by_schema probably have to go.
